import React, {useState,useEffect,useRef,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {motion, AnimatePresence, MotionConfig, useReducedMotion} from 'motion/react';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowUpRight,ArrowDown,ArrowRight,X,Sun,Moon,Pause,Play,Plus,Minus,RotateCcw,Github,MoveUpRight,Menu} from 'lucide-react';
import './styles.css';

const topics=[
 {name:'AI inference',short:'AI',color:'#8faad4',description:'What happens between a model and the machine that runs it?',target:'inference'},
 {name:'Systems',short:'SYS',color:'#c9e778',description:'How do operating-system choices shape real performance?',target:'inference'},
 {name:'Privacy',short:'PRV',color:'#ddadbd',description:'How can useful AI coexist with the protection of personal information?',target:'privacy'}
];
const work=[
 {id:'inference',type:'Research manuscript',year:'2026',title:'Looking beneath the model.',subtitle:'Operating-system tuning for AI inference',tags:['Linux','AI inference','Performance'],full:'Operating System Level Optimization for Energy Efficient AI Inference Performance',intro:'Model performance depends on more than the model. This work studies how the operating system and hardware configuration affect inference workloads.',overview:'The study explores Linux configuration for ResNet-50 and YOLOv8, looking at the relationship between CPU scheduling, GPU settings, batch sizes and thread management.',method:'The manuscript compares inference workloads across system configurations using latency, throughput and resource utilisation. The focus is on understanding which parts of the execution environment influence model performance.',question:'How do tuning choices transfer between models and workloads? How should experiments separate throughput improvements from energy consumption and latency trade-offs?',kind:'systems'},
 {id:'privacy',type:'Publication · Cureus',year:'2026',title:'Innovation, with boundaries.',subtitle:'AI and Privacy: Balancing Innovation with Security',tags:['AI','Privacy','Security'],full:'AI and Privacy: Balancing Innovation with Security',intro:'AI creates new possibilities for working with data. It also raises questions about what information systems should collect, expose and protect.',overview:'Research on the relationship between AI innovation, personal information and security. It considers privacy as part of how AI systems are designed and used.',method:'The publication examines AI and privacy through the lens of protecting personal information. Its central topic connects the usefulness of AI applications with the responsibilities involved in handling data.',question:'What information does an AI application actually need? Where can personal data be removed or protected while retaining the usefulness of the system?',kind:'privacy'},
 {id:'recruitment',type:'Industry project · Dell',year:'2026',title:'Connecting the moving parts.',subtitle:'AI recruitment assistant',tags:['Python','FastAPI','n8n'],full:'AI recruitment assistant',intro:'Backend services and automation workflows for an AI recruitment assistant, developed during my internship at Dell Technologies.',overview:'Built Python and FastAPI backend services and REST APIs. Developed n8n workflows connecting AI agents, external APIs and multi-step tasks.',method:'The work brought together API development and workflow orchestration: exposing backend functionality and coordinating the steps needed by the assistant.',question:'How should multi-step AI workflows handle failures and make their behaviour easy to inspect?',kind:'software'},
 {id:'portfolio',type:'Personal project · In progress',year:'2026',title:'From trades to a system.',subtitle:'Portfolio & trade management',tags:['Java','BigDecimal','Domain modelling'],full:'Portfolio & trade management',intro:'A Java project for learning the domain logic behind portfolios, holdings and trade operations.',overview:'The current implementation models portfolio balances, holdings, buy and sell operations, and realised profit and loss.',method:'The core domain is implemented in Java, using BigDecimal for monetary values. Development starts with the behaviour of portfolios and holdings before adding an API or database.',question:'The next direction is to connect the domain model to an API and persistent storage, then explore risk analytics. These are planned extensions, not completed features.',kind:'finance'}
];
const experience=[
 {date:'JUN — AUG 2026',title:'AI Intern',org:'Dell Technologies',place:'Dubai, UAE',body:'Built Python and FastAPI backend services for an AI recruitment assistant. Developed n8n workflows connecting agents, APIs and multi-step tasks.'},
 {date:'JUN — AUG 2023',title:'Research Assistant Intern',org:'Manipal Institute of Higher Education',place:'Dubai, UAE',body:'Analysed research datasets with Python, NumPy and TensorFlow. Created Power BI visualisations and contributed to literature reviews and research writing.'}
];
const education=[
 {date:'2026 — 2028',title:'BEng Electronics & Computer Science',org:'University of Edinburgh',place:'Edinburgh, UK',body:'Year 3 entry. Expected graduation in 2028. Developing the electronics side of my work alongside software and systems.'},
 {date:'TRANSFERRED IN 2026',title:'BTech Computer Science & Engineering (AI & ML)',org:'Vellore Institute of Technology',place:'Vellore, India',body:'Transferred after Year 2. CGPA: 8.75/10.'}
];
const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.12},transition:{duration:.65}};
function Label({children}){return <div className="eyebrow">{children}</div>}
function Arrow({size=18}){return <ArrowUpRight size={size} strokeWidth={1.5}/>}

function Atlas({active,setActive,paused,dark,open}){
 const canvas=useRef(null), rotation=useRef({x:.12,y:.1}),drag=useRef(null),pointer=useRef({x:-999,y:-999});
 const points=useMemo(()=>Array.from({length:540},(_,i)=>{const group=i%3,j=Math.floor(i/3),a=j*2.39996,r=Math.sqrt((j+.5)/180);return{group,x:Math.cos(a)*r*.53,y:Math.sin(a)*r*.7,z:Math.sin(j*7.2)*.35,j}}),[]);
 useEffect(()=>{
  const el=canvas.current,ctx=el.getContext('2d');if(!ctx)return;
  let raf,width=500,height=420,visible=true,frame=0;
  const resize=new ResizeObserver(([entry])=>{width=entry.contentRect.width;height=entry.contentRect.height;const d=Math.min(devicePixelRatio||1,2);el.width=width*d;el.height=height*d;ctx.setTransform(d,0,0,d,0,0);frame=0});resize.observe(el);
  const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting});observer.observe(el);
  const draw=()=>{
   raf=requestAnimationFrame(draw);if(!visible||document.hidden)return;if(paused&&frame>1)return;frame++;
   const t=paused?0:performance.now()*.00015;ctx.clearRect(0,0,width,height);const s=Math.min(width/3.0,height/2.8);
   const centers=[[-.68,-.42,0],[.65,-.26,.1],[0,.58,-.1]], projected=[];
   const rx=rotation.current.x, ry=rotation.current.y+(paused?0:Math.sin(t)*.15);
   for(const p of points){const c=centers[p.group];let x=p.x+c[0],y=p.y+c[1],z=p.z+c[2];const xx=x*Math.cos(ry)-z*Math.sin(ry), zz=x*Math.sin(ry)+z*Math.cos(ry),yy=y*Math.cos(rx)-zz*Math.sin(rx);const perspective=1/(1+zz*.15);let px=width/2+xx*s*perspective,py=height/2+yy*s*perspective;const dx=px-pointer.current.x,dy=py-pointer.current.y,dist=Math.hypot(dx,dy);if(dist<75&&dist>0){px+=dx/dist*(75-dist)*.13;py+=dy/dist*(75-dist)*.13}projected.push({x:px,y:py,z:zz,g:p.group});}
   // Sparse edges make this an explorable map of three research themes.
   ctx.lineWidth=.6;
   for(let i=0;i<projected.length;i+=6){let p=projected[i],q=projected[(i+33)%projected.length];ctx.strokeStyle=dark?'rgba(225,230,210,.10)':'rgba(50,58,43,.10)';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}
   projected.sort((a,b)=>a.z-b.z).forEach(p=>{ctx.globalAlpha=active===null?.68:p.g===active?.95:.16;ctx.fillStyle=topics[p.g].color;ctx.beginPath();ctx.arc(p.x,p.y,(p.g===active?2.25:1.55)+(p.z+.5)*.35,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;
   ctx.fillStyle=dark?'#d6d8cc':'#424a3a';ctx.font='10px monospace';ctx.fillText('x',width-26,height/2);ctx.fillText('y',width/2+10,24);
  };draw();return()=>{cancelAnimationFrame(raf);resize.disconnect();observer.disconnect()};
 },[points,active,paused,dark]);
 return <div className="atlas-panel"><div className="atlas-top"><Label>Research atlas / 01</Label><span className="tiny">Drag to rotate</span></div><div className="atlas-space"><canvas ref={canvas} aria-label="Interactive point-cloud map of AI inference, systems and privacy" onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const box=e.currentTarget.getBoundingClientRect();pointer.current={x:e.clientX-box.left,y:e.clientY-box.top};if(drag.current){rotation.current.y+=(e.clientX-drag.current.x)*.008;rotation.current.x+=(e.clientY-drag.current.y)*.008;drag.current={x:e.clientX,y:e.clientY}}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} onPointerLeave={()=>{pointer.current={x:-999,y:-999}}}/><div className="atlas-center">ideas<br/><i>in connection.</i></div></div><div className="atlas-tabs" aria-label="Explore research themes">{topics.map((t,i)=><button key={t.name} aria-pressed={active===i} onClick={()=>setActive(active===i?null:i)}><span style={{background:t.color}}/>{t.name}</button>)}</div><div className="atlas-caption" aria-live="polite">{active===null?<p>A few interests. A lot of connections.<br/><span>Select a theme to explore.</span></p>:<><p>{topics[active].description}</p><button className="text-button" onClick={()=>open(topics[active].target)}>Explore the research <Arrow size={16}/></button></>}</div></div>
}
function SystemVisual(){return <div className="system-visual"><div className="visual-meta"><span>INFERENCE / EXECUTION PATH</span><span>01</span></div><div className="pipeline"><div className="pipeline-unit"><span className="mono">01</span><strong>Input</strong><small>workload</small></div><div className="wire"><i/></div><div className="pipeline-unit core"><span className="mono">02</span><strong>System</strong><small>schedule · execute</small><div className="core-grid">{Array.from({length:12},(_,i)=><i key={i} style={{animationDelay:`${i*.12}s`}}/>)}</div></div><div className="wire"><i/></div><div className="pipeline-unit"><span className="mono">03</span><strong>Output</strong><small>inference</small></div></div><div className="visual-bottom"><span>CPU ↔ GPU</span><span>LATENCY / THROUGHPUT</span></div></div>}
function PrivacyVisual(){return <div className="privacy-visual"><div className="visual-meta"><span>DATA / VISIBILITY</span><span>02</span></div><div className="privacy-lines"><span>Useful information.</span><span className="private-line">Personal information.<span className="redaction"/></span><span>A considered boundary.</span></div><div className="visual-bottom"><span className="privacy-pill">Privacy by design</span><span>CONCEPTUAL ILLUSTRATION</span></div></div>}
function CaseStudy({item,close}){
 const [tab,setTab]=useState('Overview');
 useEffect(()=>setTab('Overview'),[item?.id]);
 return <Dialog.Root open={!!item} onOpenChange={v=>{if(!v)close()}}><AnimatePresence>{item&&<Dialog.Portal forceMount><Dialog.Overlay asChild><motion.div className="dialog-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/></Dialog.Overlay><Dialog.Content asChild aria-describedby="case-intro"><motion.div className="case-dialog" initial={{opacity:0,y:35,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:25}} transition={{duration:.25}}><div className="case-top"><Label>{item.type} / {item.year}</Label><Dialog.Close className="icon-button" aria-label="Close case study"><X size={22}/></Dialog.Close></div><Dialog.Title>{item.full}</Dialog.Title><Dialog.Description id="case-intro">{item.intro}</Dialog.Description><div className="tag-row">{item.tags.map(t=><span key={t}>{t}</span>)}</div>{item.id==='inference'?<SystemVisual/>:item.id==='privacy'?<PrivacyVisual/>:<div className="software-flow">{(item.id==='recruitment'?['Request','API','Workflow','Response']:['Portfolio','Order','Holding','P&L']).map((n,i)=><React.Fragment key={n}><span>{n}</span>{i<3&&<ArrowRight size={18}/>}</React.Fragment>)}</div>}<div className="case-tabs" role="tablist" aria-label="Case study sections">{['Overview','Approach','Open questions'].map((t,i)=><button key={t} id={'case-tab-'+i} role="tab" aria-controls="case-panel" aria-selected={tab===t} tabIndex={tab===t?0:-1} onClick={()=>setTab(t)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const j=(i+(e.key==='ArrowRight'?1:2))%3;setTab(['Overview','Approach','Open questions'][j]);document.getElementById('case-tab-'+j)?.focus()}}}>{t}</button>)}</div><AnimatePresence mode="wait"><motion.div id="case-panel" role="tabpanel" aria-labelledby={'case-tab-'+['Overview','Approach','Open questions'].indexOf(tab)} key={tab} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="case-copy"><h3>{tab==='Overview'?'The work':tab==='Approach'?'How it comes together':'What comes next?'}</h3><p>{tab==='Overview'?item.overview:tab==='Approach'?item.method:item.question}</p></motion.div></AnimatePresence><div className="case-footer"><span>Prada / Selected work</span><Dialog.Close className="text-button">Back to the portfolio <ArrowRight size={16}/></Dialog.Close></div></motion.div></Dialog.Content></Dialog.Portal>}</AnimatePresence></Dialog.Root>
}
function Resume(){const [tab,setTab]=useState('Experience'),[expanded,setExpanded]=useState(0);return <div className="resume-panel"><div className="resume-head"><Label>The path so far</Label><div className="segmented" aria-label="Résumé view">{['Experience','Education'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setExpanded(0)}}>{t}</button>)}</div></div><AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}}>{(tab==='Experience'?experience:education).map((x,i)=><div className="resume-row" key={x.org}><button className="resume-toggle" aria-expanded={expanded===i} aria-controls={'resume-detail-'+i} onClick={()=>setExpanded(expanded===i?null:i)}><span><small>{x.date}</small><strong>{x.org}</strong><span>{x.title}</span></span>{expanded===i?<Minus size={18}/>:<Plus size={18}/>}</button><AnimatePresence>{expanded===i&&<motion.div id={'resume-detail-'+i} initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="resume-detail"><p>{x.body}</p><small>{x.place}</small></motion.div>}</AnimatePresence></div>)}</motion.div></AnimatePresence></div>}
function SkillTable(){const bound=useRef(null),[reset,setReset]=useState(0);return <div className="skill-panel"><div className="resume-head"><div><Label>Things I work with</Label><span className="tiny">Pick them up. Move them around.</span></div><button className="icon-button" aria-label="Reset skill positions" onClick={()=>setReset(x=>x+1)}><RotateCcw size={16}/></button></div><div className="skill-table" ref={bound} key={reset}>{['Python','Java','C++','FastAPI','NumPy','TensorFlow','Linux','Git','n8n','SQL','Verilog¹','Power BI'].map((x,i)=><motion.span className={'skill skill-'+i%3} drag dragConstraints={bound} dragElastic={.08} dragMomentum={false} whileDrag={{scale:1.12,zIndex:2,rotate:0}} initial={{rotate:(i%3-1)*6}} key={x}>{x}</motion.span>)}</div><span className="tiny">¹ Verilog through coursework</span></div>}
function App(){
 const reduced=useReducedMotion();const [dark,setDark]=useState(()=>{try{return localStorage.getItem('portfolio-theme')==='dark'}catch{return false}}),[paused,setPaused]=useState(false),[active,setActive]=useState(null),[selected,setSelected]=useState(null),[nav,setNav]=useState('research'),[menu,setMenu]=useState(false);
 const still=paused||!!reduced;
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';try{localStorage.setItem('portfolio-theme',dark?'dark':'light')}catch{}},[dark]);
 useEffect(()=>{const check=()=>{const id=location.hash.slice(1);if(id.startsWith('work/'))setSelected(work.find(x=>x.id===id.slice(5))||null);else setSelected(null)};check();addEventListener('hashchange',check);return()=>removeEventListener('hashchange',check)},[]);
 const opener=useRef(null);const open=id=>{opener.current=document.activeElement;location.hash='work/'+id};const close=()=>{history.replaceState(null,'',location.pathname+location.search+'#research');setSelected(null);requestAnimationFrame(()=>opener.current?.focus())};
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setNav(e.target.id)},{rootMargin:'-20% 0px -45% 0px'});document.querySelectorAll('section[id]').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
 const revealProps=still?{}:reveal;
 return <MotionConfig reducedMotion={still?'always':'user'}><div className={still?'app paused':'app'}><a className="skip-link" href="#research">Skip to research</a><header className="site-nav"><a href="#top" className="wordmark">prada<span>*</span></a><nav aria-label="Main navigation" className={menu?'mobile-open':''}>{[['research','Selected work'],['about','About'],['journey','Experience']].map(([id,name])=><a key={id} className={nav===id?'current':''} href={'#'+id} onClick={()=>setMenu(false)}>{name}</a>)}</nav><div className="nav-tools"><a className="github-link" href="https://github.com/drunkprada" target="_blank" rel="noreferrer" aria-label="Prada on GitHub"><Github size={18}/></a><button className="icon-button motion-toggle" aria-label={paused?'Resume animations':'Pause animations'} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button className="icon-button" aria-label={dark?'Switch to light theme':'Switch to dark theme'} onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button mobile-toggle" aria-label="Toggle menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button></div></header>
 <main><div className="hero wrap" id="top"><motion.div className="hero-copy" initial={still?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7}}><Label>Prada / Electronics & Computer Science</Label><h1>Curious about<br/>what’s<br/><em>underneath.</em><span className="period">*</span></h1><p>I’m a student at the University of Edinburgh,<br className="desktop-break"/> exploring the connections between <strong>AI,<br className="desktop-break"/> systems, and the way we build things.</strong></p><a className="primary-button" href="#research">A closer look at my work <ArrowDown size={17}/></a><div className="hero-footnote"><span>BASED IN EDINBURGH, UK</span><span>RESEARCH + ENGINEERING</span></div></motion.div><motion.div initial={still?false:{opacity:0}} animate={{opacity:1}} transition={{duration:1,delay:.2}}><Atlas active={active} setActive={setActive} paused={still} dark={dark} open={open}/></motion.div></div>
 <div className="affiliation-wrap wrap"><Label>Learning & building at</Label><div className="affiliations"><span className="edinburgh">University of<br/><b>Edinburgh</b></span><span className="dell">Dell<span> Technologies</span></span><span className="vit">VIT<span>Vellore Institute of Technology</span></span><span className="manipal">MANIPAL<span>Academy of Higher Education</span></span></div></div>
 <section className="wrap work-section" id="research"><motion.div className="section-title" {...revealProps}><div><Label>01 / Selected work</Label><h2>A few questions<br/>I’ve spent time <em>with.</em></h2></div><p>Research and applied work.<br/>Open a story to look a little closer.</p></motion.div><div className="research-grid">{work.slice(0,2).map((w,i)=><motion.button className="research-card" key={w.id} {...revealProps} onClick={()=>open(w.id)} aria-label={'Read case study: '+w.full} whileHover={still?{}:{y:-6}}>{i===0?<SystemVisual/>:<PrivacyVisual/>}<div className="research-info"><div className="meta-line"><span>{w.type}</span><span>{w.year}</span></div><div className="research-title"><h3>{w.title}</h3><span className="round-arrow"><Arrow size={22}/></span></div><p>{w.subtitle}</p><div className="tag-row">{w.tags.map(t=><span key={t}>{t}</span>)}</div></div></motion.button>)}</div>
 <div className="project-list">{work.slice(2).map((w,i)=><motion.button {...revealProps} key={w.id} className="project-row" onClick={()=>open(w.id)} aria-label={'Read case study: '+w.subtitle}><div className={'project-glyph glyph-'+i}>{i===0?<span>api<span className="blinking">_</span></span>:<span>₹ <small>↗</small></span>}</div><div className="project-copy"><Label>{w.type}</Label><h3>{w.subtitle}</h3><p>{i===0?'APIs, agents and the workflows between them.':'Modelling portfolios, holdings and trade operations in Java.'}</p></div><div className="project-tools">{w.tags.slice(0,2).join(' / ')}</div><Arrow size={24}/></motion.button>)}</div></section>
 <section id="about" className="about-section"><div className="wrap"><motion.div className="about-intro" {...revealProps}><div><Label>02 / Beyond the abstract</Label><h2>I like knowing<br/><em>how things work.</em></h2></div><div><p>My work so far has taken me from AI research to backend development. Now, studying Electronics and Computer Science at Edinburgh, I’m getting closer to the hardware too.</p><p>I enjoy picking up something unfamiliar, asking questions, and building enough of it to understand what’s actually going on.</p><span className="about-note">Still learning. Usually building something.</span></div></motion.div><div className="about-bento"><motion.div {...revealProps}><SkillTable/></motion.div><motion.div className="now-panel" {...revealProps}><Label>On my desk right now</Label><h3>Java.<br/>Circuits.<br/><em>A lot of questions.</em></h3><div className="now-bottom"><span>Year 3 · BEng E&CS</span><span>Edinburgh, UK <MoveUpRight size={16}/></span></div></motion.div></div></div></section>
 <section className="wrap journey-section" id="journey"><motion.div className="section-title" {...revealProps}><div><Label>03 / The journey</Label><h2>A little context.</h2></div><p>From research to industry,<br/>and back to the classroom.</p></motion.div><motion.div {...revealProps}><Resume/></motion.div></section>
 <footer className="wrap"><div className="footer-main"><div><Label>Thanks for stopping by</Label><h2>More to <em>come.</em><span>*</span></h2></div><a className="primary-button" href="https://github.com/drunkprada" target="_blank" rel="noreferrer">Follow what I’m building <Arrow size={18}/></a></div><div className="footer-bottom"><span>Prada · Research & Engineering</span><span>Edinburgh / <Clock/></span><a href="#top">Back to top ↑</a></div></footer></main><CaseStudy item={selected} close={close}/></div></MotionConfig>
}
function Clock(){const [time,setTime]=useState('');useEffect(()=>{const tick=()=>setTime(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit'}).format(new Date()));tick();const timer=setInterval(tick,60000);return()=>clearInterval(timer)},[]);return <span>{time}</span>}
createRoot(document.getElementById('root')).render(<App/>);
